<?php

/**
 * @file
 * Contains news_archive.module.
 */

/**
 * Implements hook_theme().
 */
function news_archive_theme($existing, $type, $theme, $path) {
  return [
    'news_archive_block' => [
      'variables' => [
        'items' => [],
        'total' => 0,
        'years' => [],
        'months' => [],
        'current_year' => NULL,
        'current_month' => NULL,
        'pager' => [
          '#type' => 'pager',
          '#quantity' => 5,
        ],
      ],
    ],
  ];
}
