<?php

/**
 * @file
 * Contains twig_addons.module.
 */

use Drupal\Core\Render\Markup;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twig_addons_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twig_addons module.
    case 'help.page.twig_addons':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom twig addons') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function twig_addons_page_attachments(&$page) {

  $javascript_header = "Rot13={map:null,convert:function(e){Rot13.init();var t=\"\";for(i=0;i<e.length;i++){var n=e.charAt(i);t+=n>=\"A\"&&n<=\"Z\"||n>=\"a\"&&n<=\"z\"?Rot13.map[n]:n}return t},init:function(){if(Rot13.map!=null)return;var e=new Array;var t=\"abcdefghijklmnopqrstuvwxyz\";for(i=0;i<t.length;i++)e[t.charAt(i)]=t.charAt((i+13)%26);for(i=0;i<t.length;i++)e[t.charAt(i).toUpperCase()]=t.charAt((i+13)%26).toUpperCase();Rot13.map=e},write:function(e){document.write(Rot13.convert(e))}}";
  $page['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#value' => Markup::create($javascript_header),
    ],
    'email_obfuscator',
  ];
}
