<?php

/**
 * @file
 * Contains breadcrumbs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function breadcrumbs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the breadcrumbs module.
    case 'help.page.breadcrumbs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Outputs breadcrumbs based on main menu content.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function breadcrumbs_theme($existing, $type, $theme, $path) {
  return [
    'breadcrumbs_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
  ];
}
